apiVersion: v1
kind: Service
metadata:
  name: shiny-service
spec:
  selector:
    app: shiny-server
  ports:
  - port: 3838
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: shiny-ssl-ingress
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
  namespace: default
spec:
  rules:
  - host: shiny.example.com
    http:
      paths:
      - backend:
          serviceName: nginx-shiny-ssl-service
          servicePort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiny-server
  labels:
    app: shiny-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shiny-server
  template:
    metadata:
      labels:
        app: shiny-server
    spec:
      containers:
      - name: shiny-server
        image: nexus.example.com:8443/repository/docker-repo/shiny-server:1.5.9.923
        ports:
        - containerPort: 3838
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 3838
          initialDelaySeconds: 30
          timeoutSeconds: 30
        volumeMounts:
        - mountPath: /home
          name: home
        - mountPath: /oracle/network/admin/tnsnames.ora
          name: tnsnames-ora
          subPath: tnsnames.ora
          readOnly: true
        - mountPath: /exasol/.odbc.ini
          name: odbc-ini
          subPath: .odbc.ini
          readOnly: true
        volumeMounts:
      volumes:
      - nfs:
          path: /home
          server: 10.1.1.10
        name: home
      - configMap:
          name: tnsnames
        name: tnsnames-ora
      - configMap:
          name: odbc
        name: odbc-ini
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tnsnames
  namespace: default
data:
  tnsnames.ora: |
    RTDW-PERSONAL=
    (DESCRIPTION =
      (LOAD_BALANCE=ON)
      (FAILOVER=ON)
      (ADDRESS_LIST=
        (ADDRESS = (PROTOCOL = TCP)(HOST = ora.example.com)(PORT = 1521))
      )
      (CONNECT_DATA =
        (FAILOVER_MODE=(TYPE=SESSION)(METHOD=SELECT)(RETRIES=8)(DELAY=1))
        (SERVICE_NAME = BI_ASIA)
      )
    )
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odbc
  namespace: default
data:
  .odbc.ini: |
    [ODBC Data Sources]
    exasolution-uo2214lv2_64 = unixODBC 2.2.14 or later, libversion 2 (64bit)

    [exasolution-uo2214lv2_64]
    DRIVER = /exasol/EXASOL_ODBC-7.1.2/lib/linux/x86_64/libexaodbc-uo2214lv2.so
    EXAHOST = 10.1.1.11..25:8563

