apiVersion: v1
kind: Service
metadata:
  name: sftp-server-service
spec:
  selector:
    app: sftp-server
  type: NodePort
  ports:
  - port: 2222
    nodePort: 32222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp-server
  labels:
    app: sftp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp-server
  template:
    metadata:
      labels:
        app: sftp-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - sftp-server
              topologyKey: "kubernetes.io/hostname"
            weight: 50
      containers:
      - name: sftp-server
        image: nexus.example.com:8443/repository/docker-repo/sftp-server:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 2222
        livenessProbe:
          tcpSocket:
            port: 2222
          initialDelaySeconds: 30
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /home
          name: home
        - mountPath: /home/user
          name: user
        - mountPath: /etc/sssd/sssd.conf
          name: sssd-conf
          subPath: sssd.conf
          readOnly: true
        - mountPath: /etc/ssl/certs/ldap-ca.crt
          name: internal-root-ca
          subPath: internal-root-ca.crt
          readOnly: true
        - mountPath: /etc/security/access.conf
          name: sftp-access
          subPath: access.conf
          readOnly: true
        - mountPath: /etc/pam.d/system-auth-ac
          name: system-auth
          subPath: system-auth
          readOnly: true
        - mountPath: /etc/ssh/sshd_config
          name: sshd-config
          subPath: sshd_config
          readOnly: true
      volumes:
      - nfs:
          server: 10.1.1.10
          path: /users
        name: home
      - nfs:
          server: 10.161.227.5
          path: /sftp
        name: user
      - secret:
          secretName: sssd-conf
          defaultMode: 0600
        name: sssd-conf
      - configMap:
          name: internal-root-ca
        name: internal-root-ca
      - configMap:
          name: sftp-access
        name: sftp-access
      - configMap:
          name: system-auth
        name: system-auth
      - configMap:
          name: sshd-config
        name: sshd-config

