apiVersion: v1
kind: Service
metadata:
  name: sftp-server-service
spec:
  selector:
    app: sftp-server
  type: NodePort
  ports:
  - port: 2222
    nodePort: 32222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp-server
  labels:
    app: sftp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp-server
  template:
    metadata:
      labels:
        app: sftp-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - sftp-server
              topologyKey: "kubernetes.io/hostname"
            weight: 50
      containers:
      - name: sftp-server
        image: nexus.example.com:8443/repository/docker-repo/sftp-server:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2222
        livenessProbe:
          tcpSocket:
            port: 2222
          initialDelaySeconds: 30
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /home
          name: home
      volumes:
      - nfs:
          server: 10.1.1.10
          path: /sftp
        name: home
