apiVersion: v1
kind: Service
metadata:
  name: rserve
spec:
  type: NodePort
  selector:
    app: rserve
  ports:
  - port: 6311
    nodePort: 32311
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rserve
  labels:
    app: rserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rserve
  template:
    metadata:
      labels:
        app: rserve
    spec:
      containers:
      - name: rserve
        image: nexus.example.com:8443/repository/docker-repo/rserve:1.3
        resources:
          limits:
            cpu: "1"
            memory: "32Gi"
            ephemeral-storage: "500Mi"
          requests:
            cpu: "1"
            memory: "1Gi"
            ephemeral-storage: "100Mi"
        ports:
        - containerPort: 6311
        livenessProbe:
          tcpSocket:
            port: 6311
          initialDelaySeconds: 30
          timeoutSeconds: 30
        volumeMounts:
        - mountPath: /etc/passwd.rserver
          name: rserve-passwd
          subPath: passwd.rserver
          readOnly: true
        - mountPath: /oracle/network/admin/tnsnames.ora
          name: tnsnames-ora
          subPath: tnsnames.ora
          readOnly: true
        - mountPath: /etc/odbcinst.ini
          name: odbcinst-ini
          subPath: odbcinst.ini
          readOnly: true
        - mountPath: /etc/odbc.ini
          name: odbc-ini
          subPath: odbc.ini
          readOnly: true
        - mountPath: /opt/cloudera/hiveodbc/lib/64/cloudera.hiveodbc.ini
          name: r-cloudera-hiveodbc-ini
          subPath: cloudera.hiveodbc.ini
          readOnly: true
      securityContext:
        fsGroup: 1000
      volumes:
      - secret:
          secretName: rserve-passwd
          defaultMode: 0640
        name: rserve-passwd
      - configMap:
          name: tnsnames
        name: tnsnames-ora
      - configMap:
          name: r-odbcinst-ini
        name: odbcinst-ini
      - configMap:
          name: r-odbc-ini
        name: odbc-ini
      - configMap:
          name: r-cloudera-hiveodbc-ini
        name: r-cloudera-hiveodbc-ini
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tnsnames
  namespace: default
data:
  tnsnames.ora: |
    RTDW-PERSONAL=
    (DESCRIPTION =
      (LOAD_BALANCE=ON)
      (FAILOVER=ON)
      (ADDRESS_LIST=
        (ADDRESS = (PROTOCOL = TCP)(HOST = ora.example.com)(PORT = 1521))
      )
      (CONNECT_DATA =
        (FAILOVER_MODE=(TYPE=SESSION)(METHOD=SELECT)(RETRIES=8)(DELAY=1))
        (SERVICE_NAME = BI_ASIA)
      )
    )
---

