apiVersion: v1
kind: Service
metadata:
  name: nginx-rstudio-ldap-ssl-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-rstudio-ldap-ssl
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-rstudio-ldap-ssl
  name: nginx-rstudio-ldap-ssl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-rstudio-ldap-ssl
  template:
    metadata:
      labels:
        app: nginx-rstudio-ldap-ssl
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nginx-rstudio-ldap-ssl
              topologyKey: kubernetes.io/hostname
            weight: 50
      containers:
      - image: nexus.example.com:8443/repository/docker-repo/nginx-ldap:1.19.5
        imagePullPolicy: IfNotPresent
        name: nginx-rstudio-ldap-ssl
        ports:
        - containerPort: 443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/pki/ca-trust/internal-root-ca.crt
          name: internal-root-ca
          subPath: internal-root-ca.crt
        - mountPath: /opt/nginx/conf/nginx.conf
          name: nginx-rstudio-ldap-ssl-conf
          readOnly: true
          subPath: nginx.conf
        - mountPath: /opt/nginx/conf/tls.crt
          name: nginx-cert
          readOnly: true
          subPath: tls.crt
        - mountPath: /opt/nginx/conf/tls.key
          name: nginx-key
          readOnly: true
          subPath: tls.key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: internal-root-ca
        name: internal-root-ca
      - secret:
          defaultMode: 420
          secretName: nginx-rstudio-ldap-ssl-conf
        name: nginx-rstudio-ldap-ssl-conf
      - name: nginx-cert
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: tls.crt
          secretName: rstudio-cert
      - name: nginx-key
        secret:
          defaultMode: 420
          items:
          - key: tls.key
            path: tls.key
          secretName: rstudio-cert

